project_id = "vhthbnxzvuzrwilvorgy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://e430860f-33ba-42d4-8a2c-daea01add054.sandbox.lovable.dev"
additional_redirect_urls = ["https://lovable.app", "http://localhost:5173", "http://localhost:3000", "https://e430860f-33ba-42d4-8a2c-daea01add054.sandbox.lovable.dev", "https://e430860f-33ba-42d4-8a2c-daea01add054.sandbox.lovable.dev/reset-password"]
jwt_expiry = 3600
enable_anonymous_sign_ins = false
enable_signup = true
email_double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54323

[functions.wallet-operations]
verify_jwt = true

[functions.demo-transactions]
verify_jwt = true